# Site settings
title: NIST SP 800-63 Digital Identity Guidelines-FAQ
description: "NIST Special Publication 800-63 Digital Identity Guidelines-FAQ"
baseurl: "/800-63-FAQ" # the subpath of your site, e.g. /blog
url: "https://pages.nist.gov/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude:
- ".ruby-version"
- ".jekyll-metadata"
- ".gitignore"
- ".travis.yml"
- todo.txt
- resources
- Gemfile
- Gemfile.lock
- Makefile
- vendor
- README.md
- CONTRIBUTING.md
- LICENSE.md

# GitHub information
org_name: usnistgov
repo_name: 800-63-FAQ

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: /800-63-FAQ/

host: 0.0.0.0
